UpstreamPath: /Users/silvin/dev/go/src/github.com/docker/docker-ce
UpstreamRemote: docker/docker-ce
ComponentPath: /Users/silvin/dev/go/src/github.com/docker/cli
ComponentRemote: docker/cli
ComponentResultRemote: silvin-lubecki/cli-extract
Component: cli
Tag: v17.11.0-ce-rc1