UpstreamPath: /Users/silvin/dev/go/src/github.com/docker/docker-ce-extract/docker-ce
UpstreamRemote: docker/docker-ce
ComponentPath: /Users/silvin/dev/go/src/github.com/docker/docker-ce-packaging
ComponentRemote: docker/docker-ce-packaging
ComponentResultRemote: silvin-lubecki/packaging-extract
Component: packaging
Branch: 18.03